# Kategoriespezifisches Encoder-Modell 

## Daten laden

Unabhängig vom verwendeten Modell laden wir zunächst die bereits installierten Pakete sowie unsere Textdaten und speichern diese in einem Listenobjekt:

In [30]:
#| echo: false
from transformers import logging
logging.set_verbosity_error()  # Mitteilungen muten, damit Dokuemnt ordentlich bleibt

In [31]:
import pandas as pd
from transformers import pipeline

daten = pd.read_csv("data/example_dataset.csv")
datenliste = list(daten["text"])

daten

                                                text
0  Die orthodoxe Gemeinde feiert heute #Ostern. I...
1  Vielen Dank Gregor Rutz für die Unterstützung ...
2  Wird ja immer schlimmer mit den Intoleranten d...
3  Liebe Junge, geht wählen. Kann ja nicht sein, ...
4  ‘— Das war unser EU-Wahl-Abschluss der SP– mit...
5  Aufschlussreicher Blick hinter die Mauern! Tol...
6  Denn ein Hard-Brexit würde der #EU, aber noch ...
7  Familienbonus: Es ist erstaunlich wie viele Me...
8  Integration passiert vor Ort. Deshalb arbeitet...
9  Ich frage mich: Wer ist als nächstes dran Frau...

## Klassifikation

Nun erfolgt die eigentliche Klassifikation über den `pipeline()`-Befehl. In diesem können wir je nach Bedarf noch weitere Parameter festlegen, die der Dokumentation von HuggingFace oder unserem Beispielcode im OSF entnommen werden können. Wichtig ist etwa bei kleineren Modellen das Kürzen langer Texte in Abhängigkeit der maximalen Inputlänge des gewählten Modells (z. B. `max_length = 512, truncation=True`). Die Ausführung des `pipeline()`-Befehls kann mitunter lange dauern, vor allem beim ersten Mal, da das LLM geladen werden muss.

In [32]:
sentiment_classifier = pipeline("sentiment-analysis",
                                 model="oliverguhr/german-sentiment-bert",
                                 max_length = 512, truncation=True)

ergebnis = sentiment_classifier(datenliste)
ergebnis = pd.DataFrame(classifi)
ergebnis["text"] = daten["text"]
ergebnis

      label     score                                               text
0   neutral  0.988959  Die orthodoxe Gemeinde feiert heute #Ostern. I...
1   neutral  0.753388  Vielen Dank Gregor Rutz für die Unterstützung ...
2  negative  0.976087  Wird ja immer schlimmer mit den Intoleranten d...
3  negative  0.732691  Liebe Junge, geht wählen. Kann ja nicht sein, ...
4  negative  0.903959  ‘— Das war unser EU-Wahl-Abschluss der SP– mit...
5  positive  0.942041  Aufschlussreicher Blick hinter die Mauern! Tol...
6  negative  0.685230  Denn ein Hard-Brexit würde der #EU, aber noch ...
7  negative  0.609906  Familienbonus: Es ist erstaunlich wie viele Me...
8   neutral  0.998905  Integration passiert vor Ort. Deshalb arbeitet...
9   neutral  0.950086  Ich frage mich: Wer ist als nächstes dran Frau...